[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pda_game_example = "4h7Qe3Gkcv76cSfKgTwk2bs6NPmkDoxRzhMYQxQyYZXP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
